version: '3.3'
 
services:
#   load-balancer:
#         build: 
#             context: ./load-balancer
#             dockerfile: Dockerfile
#         image: load-balancer
#         ports: 
#             - 8000:80
#         # depends_on:
#         # - front
#         restart: always
#   front:
#         build:
#             context: ./front
#             dockerfile: Dockerfile
#         image: front
#         depends_on:
#             - back
#         volumes:
#             - "./redis-vol:/data:rw"
  redis:
        image: redis:latest
        command: bash -c "redis-server --appendonly yes"
        volumes:
            - "./redis-vol:/data:rw"
  neo4j:
    image: neo4j:3.5
    restart: unless-stopped
    ports:
      - 7474:7474
      - 7473:7473
      - 7687:7687
    volumes:
      - data:/data
      - logs:/logs
    environment: 
   #   Raise memory limits
      - NEO4J_AUTH=neo4j/adminadmin
      - NEO4J_dbms_memory_pagecache_size=1G
      - NEO4J_dbms.memory.heap.initial_size=1G
      - NEO4J_dbms_memory_heap_max__size=1G
      - NEO4J_dbms.allow_upgrade=true
      - NEO4J_dbms_connector_https_advertised__address= localhost:7473
      - NEO4J_dbms_connector_http_advertised__address= localhost:7474
      - NEO4J_dbms_connector_bolt_advertised__address= localhost:7687
  # back:
  #   image: aspdocker
  #   build:
  #     context: ./back
  #     dockerfile: Dockerfile
  #   ports:
  #      - 5000:80
  #      - 5001:443
  #   depends_on:
  #       - neo4j
  #   environment: 
  #     - Kestrel\_\_Certificates\_\_Default\_\_Password=Password
  #     - ASPNETCORE_URLS=https://+;http://+
  #     - Kestrel\_\_Certificates\_\_Default\_\_Path=/app/Infrastructure/Certificate/certificate.pfx
  #   volumes:
  #       - "data:/data:rw"
  #       - D:\temp\:/app/Infrastructure/Certificate
  #       # - "./redis-vol:/data:rw"
volumes:
    # plugins:
    # data:
    # # conf:
    # # import:
    # logs: